import { NavBar } from "@/components/navbar";
import "../../styles/globals.css";
import { Footer } from "@/components/footer";
import { products, stores } from "@/db/schema";
import { db } from "@/db/db";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function StorefrontLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const addStore = await db.insert(products).values({
  //   id: 2,
  //   name: "test",
  //   price: "100",
  //   description: "test",
  //   inventory: "1",
  //   storeId: 1,
  // });
  const Myproducts = await db.select().from(products);
  console.log(Myproducts);

  return (
    <div className="min-h-screen w-full flex flex-col">
      <NavBar showSecondAnnouncementBar={true} />
      <main className="h-full flex-1">{children}</main>
      <Footer />
    </div>
  );
}
