import { NavBar } from "@/components/navbar";
import "../styles/globals.css";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen w-full flex flex-col bg-gray-50">
        <NavBar />
        <main className="h-full flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
