import { NavBar } from "@/components/navbar";
import "../styles/globals.css";
import { Footer } from "@/components/footer";
import { ClerkProvider } from "@clerk/nextjs/app-beta";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
